# Generated by Django 2.2.2 on 2019-06-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_psychologyquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologystudy',
            name='validquestions',
        ),
        migrations.AddField(
            model_name='psychologyquestion',
            name='category',
            field=models.CharField(choices=[('BIO', 'Biological'), ('COG', 'Cognitive'), ('SC', 'Social Cultural')], default='BIO', max_length=3),
        ),
        migrations.AddField(
            model_name='psychologyquestion',
            name='valid_studies',
            field=models.ManyToManyField(to='archives.PsychologyStudy'),
        ),
    ]
