# Generated by Django 2.1.1 on 2019-06-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20190625_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologystudy',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique_for_date=('experimenters', 'year', 'category')),
        ),
    ]
