# Generated by Django 2.2.2 on 2019-06-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtwall', '0006_auto_20190625_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, default='Still searching for an answer...'),
        ),
    ]
