# Generated by Django 2.2.2 on 2019-06-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtwall', '0007_auto_20190625_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='thoughtwall.Tag'),
        ),
    ]
