# Generated by Django 2.1.1 on 2019-06-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtwall', '0009_auto_20190630_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('published_date',)},
        ),
    ]
